### ISSUE TITLE
最近刚好在搞miaomiaoji,不知道是怎么得到控制参数的名字的

### ISSUE THREAD

**Issue by qwx** [ihciah/miaomiaoji-tool#2]
我逆向了新版的安卓app，发现被混淆过，通过猜猜了一部分，不知道您是怎么获取到这些名字的，也是靠慢慢分析的喵？

**Comment by ihciah** [comment]
我是去年暑假弄的，那会直接把360加固脱了然后jeb一把梭即可。

**Comment by qwx** [comment]
不知360脱壳有什么好办法，我是用在模拟器里面运行后有脚本直接导出的dex文件。

**Comment by ihciah** [comment]
我也是233333
（从折腾完开始，我的喵喵机就开始吃灰了。

**Comment by qwx** [comment]
我晚上搞了一下，发现2.0.6版本的app已经有混淆了，从3.0.5的版本来看，好像命令增加了不少，不知少年还有没有兴趣一起研究一下。

**Comment by ihciah** [comment]
我懒得搞了，本来想逆固件的结果没搞动，你有什么办法吗？

**Comment by qwx** [comment]
蓝牙抓包，把剩下的命令抓出来，起码知道是干什么的就行，我是这么想的。。

**Comment by ihciah** [comment]
本来就没有多少指令的吧应该，毕竟硬件就这么点东西。我是想改固件加点功能呢，想控制走纸的电机多次打印。（感觉在issue里讨论不太好，戳我telegram吧？我和id同名。
